export const ON_LOGIN_EMAIL_CHANGE = "ON_LOGIN_EMAIL_CHANGE";
export const ON_LOGIN_PW_CHANGE = "ON_LOGIN_PW_CHANGE";
export const AUTH0_LOGIN_SUCCESS = "AUTH0_LOGIN_SUCCESS";

export const ON_SIGNUP_EMAIL_CHANGE = "ON_SIGNUP_EMAIL_CHANGE"